### ISSUE TITLE
Format HTML validation output results

### ISSUE THREAD

**Issue by DemeSzabolcs** [atata-framework/atata-htmlvalidation#8]
Currently, in the code, the validation results are one `string`. For example `validationResult.Output` is a `string` like this:
```
C:\Project\test\Tests\bin\Debug\net6.0\HtmlValidationTemp\24d62108-ce27-46d2-aa49-4f2a312fb142.html
  91:6   error  <button> is missing required "type" attribute  element-required-attributes
  91:93  error  Class "shepherd-button" duplicated             no-dup-class

✖ 2 problems (2 errors, 0 warnings)

More information:
  https://html-validate.org/rules/element-required-attributes.html
  https://html-validate.org/rules/no-dup-class.html
```

There are specific cases, where for only one test it would be good if I could ignore specific rules. This couldn't be done with `.htmlvalidate.js` but, that should be in the build directory and if I would add this, then it would apply it to every test, not just for the one that I want to.

An array or something like that of errors would be nicer.

**Comment by YevgeniyShunevych** [comment]
Right, `validationResult.Output` is presented as a `string` currently, because this is the result that "html-validate" library returns. Technically, we can parse a text output with a help of regex, for example. I just don't very much want to add this to Atata.HtmlValidation, as there are currently 5 formatters, and they generate different output. Anyway, you can implement such output parsing on your side for default formatter result if you wish.

As an alternative solution, I can suggest specifying `HtmlValidationOptions.ConfigPath` in that particular test with a specific separate config file path.

```cs
var options = HtmlValidationOptions.Default
    .CloneWith(x => x.ConfigPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "specific.htmlvalidate.json"));

var validator = new HtmlValidator(options);
validator.Validate("...");
// or
page.ValidateHtml(options);
```

So you can create a copy of `.htmlvalidate.json` with a specific configuration. [Information about config parameter](https://html-validate.org/usage/cli.html#c-config). I guess you'll need to specify `"root": true` property in that config. Then just reference that file in options.

**Comment by DemeSzabolcs** [comment]
Thank you for the advice, I will try out, but it looks like a good alternative!
